// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using poc.api.sqlserver.Configuration;

#nullable disable

namespace poc.api.sqlserver.Migrations
{
    [DbContext(typeof(SqlServerDb))]
    partial class SqlServerDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("poc.api.sqlserver.Model.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Dell not",
                            Preco = 10000m
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Dell Teclado",
                            Preco = 199m
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Dell mouse",
                            Preco = 120m
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Dell monitor",
                            Preco = 1985m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
